appname: "RTB::Web"
layout: "main"
charset: "UTF-8"
session: Memcached
template: "template_toolkit"

engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'
      COMPILE_DIR: 'caches/templates'
      COMPILE_EXT: '.tt'
  session:
    Memcached:
      memcached_servers: 
        - 127.0.0.1:11211
  logger:
    Console:
      log_level: error

plugins:
  Emailesque:
    from: info@ai-arena.net
    ssl: 1
    driver: smtp
    host: localhost
    port: 465
    user: info@ai-arena.net
    pass: gb978302h849
  Auth::Extensible:
    disable_roles: 1
    no_default_pages: 1
    no_login_handler: 1
    login_page_handler: 'RTB::Web:login_page_handler'
    permission_denied_page_handler: 'RTB::Web:permission_denied_page_handler'
    realms:
      users:
        provider: 'Database'
  Database:
    driver: mysql
    host: localhost
    database: 'aiarena'
    username: aiarena
    password: bTs8aum3
    connection_check_threshold: 30
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
    on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
    users_table: 'users'
    users_id_column: 'id'
    users_username_column: 'username'
    users_password_column: 'password'
